version: "3.4"

services:
  node0:
    container_name: node0
    image: ipfs/ipfs-cluster:1.0.4
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: node0
      CLUSTER_SECRET: ${CLUSTER_SECRET:?err}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/172.25.0.2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: "*" # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
      IPFS_BOOTSTRAP_RM_ALL: "true"
      IPFS_API: /ip4/172.25.0.2/tcp/5001
    ports:
      - "127.0.0.1:9094:9094" # HTTP API port (allows ipfs-cluster-ctl usage on host)
      - "9095:9095" # Cluster IPFS Proxy endpoint
      - "9096:9096" # Cluster Swarm endpoint which should be open and diallable by other cluster peers.
    networks:
      ipfs-docker_default:
        ipv4_address: 172.25.0.3
    volumes:
      - node0-peer-data:/data/ipfs-cluster

volumes:
  node0-peer-data:
