version: "3.4"

services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:v0.17.0
    entrypoint: /bin/sh
    command: /etc/ipfs-config/init.sh
    environment:
      - LIBP2P_FORCE_PNET=1
    ports:
      - "4001:4001" # IPFS Swarm port - should be open to public for all nodes if possible
      - "127.0.0.1:5001:5001" # IPFS API - provides write/admin access to the node, shouldn't be exposed at all
      - "127.0.0.1:8080:8080" # IPFS Gateway - expose if needed/wanted
    volumes:
      - ./init.sh:/etc/ipfs-config/init.sh
      - ./swarm.key:/data/ipfs/swarm.key
      - ./QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub:/tmp/QmfQkD8pBSBCBxWEwFSu4XaDVSWK6bjnNuaWZjMyQbyDub
      - ipfs0-data:/data/ipfs
    networks:
      ipfs-docker_default:
        ipv4_address: 172.25.0.2
  ipdr:
    container_name: ipdr
    image: felipecruz/ipdr-server@sha256:1521cd94e12ff5e01e5f12277894eae8252fdd1fc4c28cf8ea327eb733db30c3
    entrypoint: /go/bin/ipdr
    command: server -p 5000 --ipfs-gateway http://ipfs0:8080 --ipfs-host http://ipfs0:5001
    ports:
      - "5000:5000"
    networks:
      ipfs-docker_default:
        ipv4_address: 172.25.0.4
volumes:
  ipfs0-data:

networks:
  ipfs-docker_default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.2/16
          gateway: 172.25.0.1
